// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzgNF4v1vnmjTOmyS4wgO8uUJpKsa4vKg',
    appId: '1:413283102750:android:1c6146194e69f30ace7e0f',
    messagingSenderId: '413283102750',
    projectId: 'dormbnb-3d1db',
    storageBucket: 'dormbnb-3d1db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8vNfZ-DyWoXTPtaHrQ0RQFecdObBps4M',
    appId: '1:413283102750:ios:a9c8b81772f4b71dce7e0f',
    messagingSenderId: '413283102750',
    projectId: 'dormbnb-3d1db',
    storageBucket: 'dormbnb-3d1db.firebasestorage.app',
    iosBundleId: 'com.example.dormbnb',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFEz94HKLho0yKkvIrAkDqpqhV9I7ZJJM',
    appId: '1:413283102750:web:59d8d88f7528fd70ce7e0f',
    messagingSenderId: '413283102750',
    projectId: 'dormbnb-3d1db',
    authDomain: 'dormbnb-3d1db.firebaseapp.com',
    storageBucket: 'dormbnb-3d1db.firebasestorage.app',
    measurementId: 'G-C980HY8HL3',
  );

}